/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.31
</auto-generated>
------------------------------------------------------------------------------ */

using Progress.Sitefinity.Renderer.Designers.Attributes;
using Progress.Sitefinity.Renderer.Entities.Content;
using System;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;

namespace ADA.Mvc.Models
{
    public enum Enumeration
    {
        Value1,
        Value2,
        Value3
    }
    public class HelloWorldModel
	{
        public string Message { get; set; }
        public bool Flag { get; set; }
        public Enumeration Enum { get; set; }
        public int Number { get; set; }
        public DateTime MyDate { get; set; }
        public string ImageUrl { get; set; }
        public string PressRelease { get; set; }
    }
}